version: '3'
services:
  nginx: 
    image: nginx:1.14.2
    container_name: nginx
    volumes:
      - data:/data      
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - 80:80
      - 443:443

  jenkins:
    image: jenkinsci/blueocean:1.19.0
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000

  builder:
    image: ropensci/docs:latest
    container_name: dummy

volumes:
  data:
    external: true
  jenkins-data:
